jobs:
  textConverter:
    type: App\Jobs\TextConverterJob
  preProcessor:
    type: App\Jobs\PreProcessorJob
    params:
      documents: !job textConverter
  documentClassifier:
    type: App\Jobs\DocumentClassifierJob
    params:
      documents: !job preProcessor
  documentStore:
    type: App\Stores\OpensearchStore
    params:
      documents: !job documentClassifier
      createIndex: true
      recreateIndex: true
